# permissions for end users to view shpas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shpa-viewer-role
rules:
- apiGroups:
  - webapp.my.shpa
  resources:
  - shpas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.shpa
  resources:
  - shpas/status
  verbs:
  - get
